个人dev合并团队
TalentOrg-Dev/naodongai pull request #8
Opened 2023-07-07 03:23 UTC by whpck001

增加飞书帮助和摘要功能

2023-07-07 06:07 UTC, chaonengs requested changes

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishu/[...appId].ts
> +  if (chatModeName.indexOf(JSON.parse(event.data.message.content).text)!= -1) {
没太看懂，怎么感觉用一个 text === 'help' 做判断就行了？ 你也没有要取不同的mode值啊

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishu/[...appId].ts
> +    let chatSession = await prisma.chatSession.findFirst({
为什么不用findunique

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishu/[...appId].ts
> +      defaultSelectMenu: defaultSelectMenu,
如果这个menu就是temperature, 变量名就叫temperrature，  不要叫menu

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishu/[...appId].ts
> +        let status = await chatSessionCard(client, event, app, res);
不要用这种变量名

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +  let chatSession = await prisma.chatSession.findFirst({
findunique

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +  let status = false;
不用要status这种意义不明变量名称

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +  let status=await chatSessionfindBy(groupId,sender);
不要用status，你都看下，其他地方我也不写评论了

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +  if (status) {
不要通过判断存在不存在来做，直接使用prisma的upsert

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +    res.end(JSON.stringify({ challenge: req.body['challenge'] }));
缺少了加解密的验证

2023-07-07 06:07 UTC, chaonengs commented on src/processers/feishubot.ts
> +const chatHistroyMessage = (messages: Array, chatHistroy: JSON) => {
你这个方法是组装mesasge的，应该return {messages, promptTokens} ， chatHistory也不该是json类型，写个飞书结果的type

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +    } else {
移除else

2023-07-07 06:07 UTC, chaonengs commented on src/pages/api/feishuCard/[...appId].ts
> +};
添加如果所有if都不命中，如何处理的代码

2023-07-07 06:07 UTC, chaonengs commented on src/processers/feishubot.ts
> +    let endTime = Math.floor(Date.now() / 1000);
用next的now方法，返回timpstamp 秒数的

2023-07-07 06:07 UTC, chaonengs commented on src/processers/feishubot.ts
> +  const feishuHistory = await feishuHistoryMakeMessages(receivedMessage, accessToken);
先判断是不是摘要，再做对应逻辑，不要两个东西放一个方法里，可读性不佳

2023-07-07 06:19 UTC, whpck001 commented on src/pages/api/feishu/[...appId].ts
> +  if (chatModeName.indexOf(JSON.parse(event.data.message.content).text)!= -1) {
帮助在钉钉已经用了，就直接引用钉钉的帮助，不准备用写死的字符串

2023-07-07 06:36 UTC, chaonengs commented on src/pages/api/feishu/[...appId].ts
> +  if (chatModeName.indexOf(JSON.parse(event.data.message.content).text)!= -1) {
但你这个可读性很差，如果这里只有判断是不是help，不要用这么麻烦的代码

2023-07-11 05:59 UTC, chaonengs approved these changes

2023-07-11 05:59 UTC, chaonengs commented on prisma/schema.prisma
> +  temperature    Json?
为什么是json？

2023-07-11 05:59 UTC, chaonengs commented on src/pages/api/feishu/[...appId].ts
> +  if (chatModeName.indexOf(JSON.parse(event.data.message.content).text)!= -1) {
如果你要用统一的指令集的方法，那就实现完整的指令集，不要只有一个  let chatModeName = ChatModeTypes[0].name;

2023-07-11 06:00 UTC, merged